# Generated by Django 5.2.2 on 2025-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOfficer',
            fields=[
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, default='', max_length=40)),
                ('phone_number', models.CharField(max_length=14)),
                ('official_email', models.EmailField(max_length=254)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
