# Generated by Django 5.2.2 on 2025-06-08 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('staff', '0001_initial'),
        ('users', '0002_remove_user_is_email_verified_user_lga_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccount',
            name='user',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('account_level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], default='1')),
                ('CLASS', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_PND_active', models.BooleanField(default=False)),
                ('is_dormant', models.BooleanField(default=False)),
                ('account_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='staff.accountofficer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentAccount',
        ),
        migrations.DeleteModel(
            name='SavingsAccount',
        ),
    ]
