# Generated by Django 5.2.2 on 2025-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='lga_of_origin',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
